using System;
using System.IO;
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.XR.Management;
#endif
using UnityEngine.XR.Management;
using UnityEngine.XR.OpenXR.Features;
using UnityEngine.XR.OpenXR.Features.Mock;

namespace UnityEngine.XR.OpenXR.TestTooling
{
    /// <summary>
    /// Generates blank OpenXR settings and loader assets for testing purposes, while
    /// preserving existing settings to be restored after testing is completed.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Use this class to activate and get OpenXR features, and add OpenXR extension strings.
    /// </para>
    /// <para>
    /// Instances of this class are generated by <see cref="MockOpenXREnvironment"/> when
    /// setting up a Mock XR environment, so you do not need to create instances of this class directly.
    /// Instead, use <see cref="MockOpenXREnvironment"/> to obtain an instance of the settings used by the environment.
    /// </para>
    /// </remarks>
    internal class MockOpenXREnvironmentSettings : IDisposable
    {
        static readonly string[] s_TestGeneralSettings = { "Temp", "Test" };
        static readonly string[] s_TempSettingsPath = { "Temp", "Test", "Settings" };
        const string k_OpenXRSettingsKey = "OpenXRTestSettings";

        string m_TestPathToGeneralSettings;
        string m_TestPathToSettings;

        string m_OriginalOpenXRExtensionStrings;

#if UNITY_EDITOR
        OpenXRLoader m_OpenXrLoader = null;
        OpenXRSettings m_OpenXrSettings = null;

        XRManagerSettings m_TestManagerSettings = null;
        XRGeneralSettings m_TestXrGeneralSettings = null;

        XRGeneralSettings m_OriginalSettings = null;
        XRGeneralSettingsPerBuildTarget m_BuildTargetSettings = null;
#endif

        static bool AnyLoaderIsRunning => OpenXRLoaderBase.Instance != null;

        internal MockOpenXREnvironmentSettings()
        {
            BackupOriginalSettings();

            CreateXrManagementAssets();

            CreateXRLoaderAndXRSettings();

#if UNITY_EDITOR
            UnityEditor.XR.OpenXR.Features.FeatureHelpers.RefreshFeatures(BuildTargetGroup.Standalone);
            UnityEditor.XR.OpenXR.Features.FeatureHelpers.RefreshFeatures(BuildPipeline.GetBuildTargetGroup(UnityEditor.EditorUserBuildSettings.activeBuildTarget));
#endif
        }

        /// <summary>
        /// Disposes the MockXR environment settings and restores any backed up settings.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This method does nothing if the MockXR environment settings have already been disposed.
        /// </para>
        /// <para>
        /// Usually, this method will be called automatically by the <see cref="MockOpenXREnvironment"/>
        /// this instance is associated with.
        /// </para>
        /// </remarks>
        public void Dispose()
        {
            RemoveLoaderAndSettings();
            RemoveXrManagerAssets();
            RestoreOriginalSettings();
        }

        void BackupOriginalSettings()
        {
            m_OriginalOpenXRExtensionStrings = MockRuntime.Instance.openxrExtensionStrings;
#if UNITY_EDITOR
            if (XRGeneralSettings.Instance != null)
            {
                m_OriginalSettings = XRGeneralSettings.Instance;
            }
#endif
        }

        void RestoreOriginalSettings()
        {
#if UNITY_EDITOR
            if (m_OriginalSettings != null)
            {
                XRGeneralSettings.Instance = m_OriginalSettings;
            }
#endif
            MockRuntime.Instance.openxrExtensionStrings = m_OriginalOpenXRExtensionStrings;
        }

        void CreateXrManagementAssets()
        {
#if UNITY_EDITOR
            // Create mock for platform-specific XR settings
            m_TestPathToGeneralSettings = GetAssetPathForComponents(s_TestGeneralSettings);
            m_TestPathToGeneralSettings = Path.Combine(m_TestPathToGeneralSettings, "Test_XRGeneralSettingsPerBuildTarget.asset");
            if (File.Exists(m_TestPathToGeneralSettings))
            {
                AssetDatabase.DeleteAsset(m_TestPathToGeneralSettings);
            }

            m_BuildTargetSettings = ScriptableObject.CreateInstance<XRGeneralSettingsPerBuildTarget>();
            AssetDatabase.CreateAsset(m_BuildTargetSettings, m_TestPathToGeneralSettings);

            // Create mock for general XR settings
            m_TestPathToSettings = GetAssetPathForComponents(s_TempSettingsPath);
            m_TestPathToSettings = Path.Combine(m_TestPathToSettings, "Test_XRGeneralSettings.asset");
            if (File.Exists(m_TestPathToSettings))
            {
                AssetDatabase.DeleteAsset(m_TestPathToSettings);
            }

            m_TestManagerSettings = ScriptableObject.CreateInstance<XRManagerSettings>();

            m_TestXrGeneralSettings = ScriptableObject.CreateInstance<XRGeneralSettings>();
            XRGeneralSettings.Instance = m_TestXrGeneralSettings;
            m_TestXrGeneralSettings.Manager = m_TestManagerSettings;

            m_BuildTargetSettings.SetSettingsForBuildTarget(BuildTargetGroup.Standalone, m_TestXrGeneralSettings);
            m_BuildTargetSettings.SetSettingsForBuildTarget(GetBuildTargetGroup(), m_TestXrGeneralSettings);

            AssetDatabase.CreateAsset(m_TestXrGeneralSettings, m_TestPathToSettings);
            AssetDatabase.AddObjectToAsset(m_TestManagerSettings, m_TestXrGeneralSettings);

            AssetDatabase.SaveAssets();

            EditorBuildSettings.AddConfigObject(XRGeneralSettings.k_SettingsKey, m_BuildTargetSettings, true);
#endif
        }

        void CreateXRLoaderAndXRSettings()
        {
#if UNITY_EDITOR
            // Setup Loader
            var path = GetAssetPathForComponents(s_TempSettingsPath);
            var loaderPath = Path.Combine(path, $"Test_{typeof(OpenXRLoader).Name}.asset");
            m_OpenXrLoader = GetOrCreateAsset<OpenXRLoader>(loaderPath);

#pragma warning disable CS0618
            m_TestXrGeneralSettings?.Manager.loaders.Clear();
            m_TestXrGeneralSettings?.Manager.loaders.Add(m_OpenXrLoader);
#pragma warning restore CS0618

            // Setup Settings
            var settingsPath = Path.Combine(path, $"Test_{typeof(OpenXRSettings).Name}.asset");
            m_OpenXrSettings = GetOrCreateAsset<OpenXRSettings>(settingsPath);

            EditorBuildSettings.AddConfigObject(k_OpenXRSettingsKey, m_OpenXrSettings, true);
#endif
        }

        void RemoveLoaderAndSettings()
        {
#if UNITY_EDITOR
            var path = GetAssetPathForComponents(s_TempSettingsPath);
            var loaderPath = Path.Combine(path, $"Test_{typeof(OpenXRLoader).Name}.asset");
            AssetDatabase.DeleteAsset(loaderPath);

            EditorBuildSettings.RemoveConfigObject(k_OpenXRSettingsKey);
#endif
        }

        void RemoveXrManagerAssets()
        {
#if UNITY_EDITOR
            // Destroy MockRuntime assets (from LoaderTestSetup.cs)
            var path = GetAssetPathForComponents(s_TempSettingsPath);
            var settingsPath = Path.Combine(path, $"Test_{typeof(OpenXRSettings).Name}.asset");
            AssetDatabase.DeleteAsset(settingsPath);

            // Destroy XR Management Assets (from ManagementTestSetup.cs)
            EditorBuildSettings.RemoveConfigObject(XRGeneralSettings.k_SettingsKey);
            m_TestManagerSettings = null;
            m_TestXrGeneralSettings = null;
            m_BuildTargetSettings = null;
            AssetDatabase.DeleteAsset(Path.Combine("Assets", "Temp"));
#endif
        }

#if UNITY_EDITOR
        static string GetAssetPathForComponents(string[] pathComponents, string root = "Assets")
        {
            if (pathComponents.Length <= 0)
                return null;

            string path = root;
            foreach (var pc in pathComponents)
            {
                string subFolder = Path.Combine(path, pc);
                bool shouldCreate = true;
                foreach (var f in AssetDatabase.GetSubFolders(path))
                {
                    if (String.Compare(Path.GetFullPath(f), Path.GetFullPath(subFolder), true) == 0)
                    {
                        shouldCreate = false;
                        break;
                    }
                }

                if (shouldCreate)
                    AssetDatabase.CreateFolder(path, pc);
                path = subFolder;
            }

            return path;
        }

        static T GetOrCreateAsset<T>(string path) where T : UnityEngine.ScriptableObject
        {
            T asset;
            if (!File.Exists(path))
            {
                asset = ScriptableObject.CreateInstance<T>();
                AssetDatabase.CreateAsset(asset, path);
                AssetDatabase.SaveAssets();
            }
            else
            {
                asset = AssetDatabase.LoadAssetAtPath<T>(path);
            }

            return asset as T;
        }
#endif

        /// <summary>
        /// Gets the instance of an OpenXR feature currently set up in the MockXR environment.
        /// </summary>
        /// <typeparam name="F">
        /// Type of the OpenXR feature to be retrieved.
        /// The feature must be a subclass of <see cref="OpenXRFeature"/>.
        /// </typeparam>
        /// <returns>
        /// The instance of the OpenXR feature or <see langword="null"/> if no feature of the
        /// specified type was found.
        /// </returns>
        internal F GetFeature<F>() where F : OpenXRFeature
        {
            return OpenXRSettings.ActiveBuildTargetInstance.GetFeature(typeof(F)) as F;
        }

        /// <summary>
        /// Activates or deactivates an OpenXR feature to be used in the Mock XR environment.
        /// </summary>
        /// <remarks>
        /// The feature status can't be changed if any OpenXR loader is running at the moment you call this method.
        /// </remarks>
        /// <typeparam name="F">
        /// Type of the OpenXR feature to be modified.
        /// The feature must be a subclass of <see cref="OpenXRFeature"/>.
        /// </typeparam>
        /// <param name="enable">Set to <c>true</c> to enable the feature; <c>false</c> to disable it</param>
        /// <returns>
        /// <c>true</c> if the feature status was changed successfully or already had the desired state.
        /// <c>false</c> if the feature status could not be changed or the feature was not found.
        /// </returns>
        internal bool EnableFeature<F>(bool enable) where F : OpenXRFeature
        {
            if (AnyLoaderIsRunning)
            {
                return false;
            }

            var feature = GetFeature<F>();
            if (feature == null)
            {
                return false;
            }

            feature.enabled = enable;
            return true;
        }

        /// <summary>
        /// Requests the use of the provided extension to the list of extensions to be requested to the Mock Runtime.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The extensions can only be added before starting the Mock XR environment. Any extension added
        /// afterwards will be ignored.
        /// </para>
        /// <para>
        /// Note that adding the extension name doesn't ensure that it will be activated, Mock Runtime must
        /// support it in order to work.
        /// </para>
        /// </remarks>
        /// <param name="extensionName">Name of the extension to add.</param>
        internal void RequestUseExtension(string extensionName)
        {
            MockRuntime.Instance.openxrExtensionStrings += $" {extensionName}";
        }

#if UNITY_EDITOR
        static BuildTargetGroup GetBuildTargetGroup()
        {
            return BuildPipeline.GetBuildTargetGroup(UnityEditor.EditorUserBuildSettings.activeBuildTarget);
        }
#endif
    }
}
